apiVersion: v1
kind: Service
metadata:
  name: {{ template "retro-user-management.fullname" . }}
  labels:
    app: {{ template "retro-user-management.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: LoadBalancer
  ports:
  - name: {{ template "retro-user-management.fullname" . }}
    port: 3000
    targetPort: 3000
  selector:
    app: {{ template "retro-user-management.fullname" . }}